using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using FluentAssertions;
using Moq;
using Xunit;

namespace AutoFixture.Extensions.Tests
{
    public class SimpleChildFixture : BaseFixtureSetup<SimpleChild>
    {
        /// <inheritdoc />
        public SimpleChildFixture(IFixture fixture) : base(fixture)
        {
        }

        /// <inheritdoc />
        public SimpleChildFixture(IFixture fixture, SimpleChild item) : base(fixture, item)
        {
        }

        /// <inheritdoc />
        public SimpleChildFixture(
            IFixture fixture,
            Func<FixtureSetupOptions<SimpleChild>, FixtureSetupOptions<SimpleChild>> options) : base(fixture, options)
        {
        }
    }

    public class SimpleChildFixtureTest
    {
        [Theory, AutoMoqData(false)]
        public Task FixtureSetup_DisableAutoGeneration_ShouldReturnDefault(IFixture fixture)
        {
            // Arrange
            var sut = new SimpleChildFixture(fixture);

            // Act
            var i0 = new SimpleChild();
            var i1 = sut.Object;
            var i2 = fixture.Create<SimpleChild>();

            // Assert
            // Should be equivalent to i0, because auto generation is disabled
            i1.Should().NotBeNull();
            i1.Should().NotBeSameAs(i0);
            i1.Should().BeEquivalentTo(i0);
            i1.Should().BeSameAs(i2);
            
            // Should be a mock
            Mock.Get(i1).Should().NotBeNull();
            i1.IsMockType().Should().BeTrue();
            sut.Mock.Should().BeSameAs(Mock.Get(i1));

            return Task.CompletedTask;
        }

        [Theory, AutoMoqData]
        public Task FixtureSetup_Default_ShouldReturnAutoGeneratedValues(IFixture fixture)
        {
            // Arrange
            var i0 = new SimpleChild();

            // Act
            var sut = new SimpleChildFixture(fixture);
            var i1 = sut.Object;
            var i2 = fixture.Create<SimpleChild>();
            i1.Should().BeSameAs(i2);

            // Assert
            var instances = new List<SimpleChild> { i1, i2 };
            foreach (var instance in instances)
            {
                instance.Should().NotBeNull();
                instance.IsMockType().Should().BeTrue();
                instance.Should().NotBeEquivalentTo(i0);
                instance.Name.Should().NotBeNullOrEmpty();
                instance.Name.Should().NotBe(i0.Name);
                instance.Number.Should().NotBe(default);
                instance.Number.Should().NotBe(i0.Number);
                instance.ConcurrencyStamp.Should().NotBe(default(Guid));
                instance.ConcurrencyStamp.Should().NotBe(i0.ConcurrencyStamp);
            }

            return Task.CompletedTask;
        }

        [Theory, AutoMoqData]
        public Task FixtureSetup_InjectItem_ShouldReturnInjectedObject(IFixture fixture)
        {
            // Arrange
            var i0 = new SimpleChild();
            var injected = new SimpleChild("OverridenText", 111)
            {
                ConcurrencyStamp = new Guid("6f55a677-c447-45f0-8e71-95c7b73fa889")
            };

            // Act
            var sut = new SimpleChildFixture(fixture, injected);
            var i1 = sut.Object;
            var i2 = fixture.Create<SimpleChild>();
            i1.Should().BeSameAs(i2);

            // Assert
            var instances = new List<SimpleChild> { i1, i2 };
            foreach (var instance in instances)
            {
                instance.Should().NotBeNull();
                instance.IsMockType().Should().BeFalse();
                instance.Should().BeOfType<SimpleChild>();
                instance.Should().NotBeEquivalentTo(i0);
                instance.Should().BeSameAs(injected);
                instance.Name.Should().Be("OverridenText");
                instance.Number.Should().Be(111);
                instance.ConcurrencyStamp.ToString().Should().Be("6f55a677-c447-45f0-8e71-95c7b73fa889");
            }

            return Task.CompletedTask;
        }

        [Theory, AutoMoqData]
        public Task FixtureSetup_InjectOptions_ShouldReturnInjectedValues(IFixture fixture)
        {
            // Arrange
            var i0 = new SimpleChild();

            // Act
            var sut = new SimpleChildFixture(fixture, options => options
                .Setup(_ => _.Name, "OverridenText")
                .Setup(_ => _.Number, 111)
                .Setup(_ => _.ConcurrencyStamp, new Guid("6f55a677-c447-45f0-8e71-95c7b73fa889"))
            );
            var i1 = sut.Object;
            var i2 = fixture.Create<SimpleChild>();
            i1.Should().BeSameAs(i2);

            // Assert
            var instances = new List<SimpleChild> { i1, i2 };
            foreach (var instance in instances)
            {
                instance.Should().NotBeNull();
                instance.IsMockType().Should().BeTrue();
                instance.Should().NotBeEquivalentTo(i0);
                instance.Name.Should().Be("OverridenText");
                instance.Number.Should().Be(111);
                instance.ConcurrencyStamp.ToString().Should().Be("6f55a677-c447-45f0-8e71-95c7b73fa889");
            }

            return Task.CompletedTask;
        }
    }
}